spring.application.name=bugtrack

spring.datasource.url=jdbc:postgresql://localhost:5432/bugtrack
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
